# Generated by Django 3.0.3 on 2020-07-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200703_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AddField(
            model_name='question',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
