# Generated by Django 3.0.3 on 2020-07-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200703_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Avocat Petrescu Carmen', max_length=80),
        ),
    ]
