# Generated by Django 3.0.3 on 2020-07-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(help_text='Pentru a completa câmpul „Slug”, apasă pe câmpul „title”', max_length=250, unique_for_date='publish'),
        ),
    ]
