# Generated by Django 3.0.3 on 2020-07-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200705_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(help_text='* Pentru a completa câmpul „Slug”, apasă pe câmpul „title”.', max_length=250, unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='* Pentru a publica pe site, selectează „published” din listă.', max_length=10),
        ),
    ]
