# Generated by Django 3.0.3 on 2020-07-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200706_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='Anonim', help_text='* Se completează doar dacă este necesar, implicit va fi Anonim.', max_length=250),
        ),
    ]
