# Generated by Django 3.0.8 on 2020-07-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_question_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comentariu',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publicat'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publicat', 'Publicat')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(help_text='* Pentru a completa câmpul „Slug”, apasă pe câmpul „title”.', max_length=250, unique_for_date='publicat'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publicat', 'Publicat')], default='draft', help_text='* Pentru a publica pe site, selectează „publicat” din listă.', max_length=10),
        ),
    ]
