# Generated by Django 3.0.8 on 2020-07-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_contact_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentariu',
            options={'ordering': ('created',), 'verbose_name_plural': 'Răspunde la întrebări'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Pagina de contact'},
        ),
        migrations.AlterModelOptions(
            name='postări',
            options={'ordering': ('-publish',), 'verbose_name_plural': 'Postările mele'},
        ),
        migrations.AlterModelOptions(
            name='întrebări',
            options={'ordering': ('-publish',), 'verbose_name_plural': 'Întrebări primite'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='postări',
            name='slug',
            field=models.SlugField(help_text='* Se completează automat.', max_length=250, unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='postări',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='* Selectează „Publicat” pentru a posta pe site.', max_length=10),
        ),
        migrations.AlterField(
            model_name='întrebări',
            name='slug',
            field=models.SlugField(help_text='* Pentru a completa câmpul „Slug”, apasă pe câmpul „title”.', max_length=250, unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='întrebări',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='* Pentru a publica pe site, selectează „publicat” din listă.', max_length=10),
        ),
    ]
