# Generated by Django 3.0.8 on 2020-07-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200722_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariu',
            name='post',
            field=models.ForeignKey(help_text='* Selectează o întrebare din listă.', limit_choices_to={'draft': True}, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Întrebări'),
        ),
    ]
