# Generated by Django 3.0.8 on 2020-07-22 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200723_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariu',
            name='post',
            field=models.ForeignKey(help_text='* Selectează o întrebare din listă.', limit_choices_to={'status': 'draft'}, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Întrebări'),
        ),
    ]
